<?php
class CreateDatabaseSchema extends CakeMigration {

/**
 * Migration description
 *
 * @var string
 * @access public
 */
	public $description = '';

/**
 * Actions to be performed
 *
 * @var array $migration
 * @access public
 */
	public $migration = array(
		'up' => array(
			'create_table' => array(
				'access_token' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'app' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 45, 'collate' => 'utf8_unicode_ci', 'comment' => '1', 'charset' => 'utf8', 'after' => 'id'),
					'user_id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'index', 'after' => 'app'),
					'token' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 80, 'key' => 'index', 'collate' => 'utf8_unicode_ci', 'comment' => '1', 'charset' => 'utf8', 'after' => 'user_id'),
					'type' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 45, 'collate' => 'utf8_unicode_ci', 'comment' => '1', 'charset' => 'utf8', 'after' => 'token'),
					'created' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'after' => 'type'),
					'expired' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'after' => 'created'),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
						'token' => array('column' => 'token', 'unique' => 0),
						'user_id' => array('column' => 'user_id', 'unique' => 0),
						'user_id_app_key_expired' => array('column' => array('user_id', 'app', 'expired'), 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_unicode_ci', 'engine' => 'InnoDB'),
				),
				'accounts' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'user_id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'index', 'after' => 'id'),
					'game_id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'index', 'after' => 'user_id'),
					'account_id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'index', 'after' => 'game_id'),
					'created' => array('type' => 'datetime', 'null' => false, 'default' => NULL, 'key' => 'index', 'after' => 'account_id'),
					'modified' => array('type' => 'datetime', 'null' => false, 'default' => NULL, 'after' => 'created'),
					'fb_id' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 45, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'modified'),
					'id_game_center' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'fb_id'),
					'email_google_play' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'id_game_center'),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
						'user_id_game_id' => array('column' => array('user_id', 'game_id'), 'unique' => 1),
						'user_id' => array('column' => 'user_id', 'unique' => 0),
						'game_id' => array('column' => 'game_id', 'unique' => 0),
						'game_id_fb_id' => array('column' => array('game_id', 'fb_id'), 'unique' => 0),
						'created' => array('column' => 'created', 'unique' => 0),
						'account_id_game_id' => array('column' => array('account_id', 'game_id'), 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_unicode_ci', 'engine' => 'InnoDB'),
				),
				'articles' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'title' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 1000, 'key' => 'index', 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'id'),
					'body' => array('type' => 'text', 'null' => false, 'default' => NULL, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'title'),
					'parsed_body' => array('type' => 'text', 'null' => false, 'default' => NULL, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'body'),
					'summary' => array('type' => 'text', 'null' => true, 'default' => NULL, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'parsed_body'),
					'user_id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'index', 'after' => 'summary'),
					'created' => array('type' => 'datetime', 'null' => false, 'default' => NULL, 'key' => 'index', 'after' => 'user_id'),
					'modified' => array('type' => 'datetime', 'null' => false, 'default' => NULL, 'after' => 'created'),
					'position' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'index', 'after' => 'modified'),
					'category_id' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10, 'key' => 'index', 'after' => 'position'),
					'type_of_category' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10, 'comment' => 'Kiểu bài viết phụ cho từng chuyên mục', 'after' => 'category_id'),
					'slug' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 1000, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'type_of_category'),
					'published' => array('type' => 'boolean', 'null' => false, 'default' => '0', 'after' => 'slug'),
					'published_date' => array('type' => 'datetime', 'null' => true, 'default' => NULL, 'key' => 'index', 'after' => 'published'),
					'is_hot' => array('type' => 'boolean', 'null' => false, 'default' => '0', 'after' => 'published_date'),
					'is_new' => array('type' => 'boolean', 'null' => false, 'default' => '0', 'after' => 'is_hot'),
					'is_event' => array('type' => 'boolean', 'null' => false, 'default' => '0', 'after' => 'is_new'),
					'website_id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'index', 'after' => 'is_event'),
					'event_start' => array('type' => 'datetime', 'null' => true, 'default' => NULL, 'after' => 'website_id'),
					'event_end' => array('type' => 'datetime', 'null' => true, 'default' => NULL, 'after' => 'event_start'),
					'key_words' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'event_end'),
					'markup' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 120, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'key_words'),
					'is_share' => array('type' => 'boolean', 'null' => true, 'default' => NULL, 'after' => 'markup'),
					'is_open_server' => array('type' => 'boolean', 'null' => true, 'default' => '0', 'after' => 'is_share'),
					'open_server_name' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'is_open_server'),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
						'position' => array('column' => 'position', 'unique' => 0),
						'user_id' => array('column' => 'user_id', 'unique' => 0),
						'category_id' => array('column' => 'category_id', 'unique' => 0),
						'title' => array('column' => 'title', 'unique' => 0, 'length' => array('255')),
						'created' => array('column' => 'created', 'unique' => 0),
						'published_date' => array('column' => 'published_date', 'unique' => 0),
						'website_id_published_event_start_event_end' => array('column' => array('website_id', 'published', 'event_start', 'event_end'), 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_unicode_ci', 'engine' => 'InnoDB'),
				),
				'categories' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'title' => array('type' => 'string', 'null' => false, 'default' => NULL, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'id'),
					'slug' => array('type' => 'string', 'null' => false, 'default' => NULL, 'key' => 'index', 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'title'),
					'description' => array('type' => 'text', 'null' => true, 'default' => NULL, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'slug'),
					'type' => array('type' => 'string', 'null' => false, 'default' => 'Article', 'length' => 45, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'description'),
					'article_count' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'after' => 'type'),
					'lft' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'after' => 'article_count'),
					'rght' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'after' => 'lft'),
					'created' => array('type' => 'datetime', 'null' => true, 'default' => NULL, 'after' => 'rght'),
					'modified' => array('type' => 'datetime', 'null' => true, 'default' => NULL, 'after' => 'created'),
					'category_id' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10, 'key' => 'index', 'after' => 'modified'),
					'website_id' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10, 'after' => 'category_id'),
					'for_dashboard' => array('type' => 'boolean', 'null' => false, 'default' => '0', 'after' => 'website_id'),
					'level' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 6, 'after' => 'for_dashboard'),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
						'Slug' => array('column' => 'slug', 'unique' => 0),
						'category_id' => array('column' => 'category_id', 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_unicode_ci', 'engine' => 'InnoDB'),
				),
				'games' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'title' => array('type' => 'string', 'null' => false, 'default' => NULL, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'id'),
					'app' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 45, 'key' => 'index', 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'title'),
					'secret_key' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 45, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'app'),
					'description' => array('type' => 'text', 'null' => true, 'default' => NULL, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'secret_key'),
					'parsed_description' => array('type' => 'text', 'null' => true, 'default' => NULL, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'description'),
					'changelog' => array('type' => 'text', 'null' => true, 'default' => NULL, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'parsed_description'),
					'parsed_changelog' => array('type' => 'text', 'null' => true, 'default' => NULL, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'changelog'),
					'released' => array('type' => 'date', 'null' => true, 'default' => NULL, 'after' => 'parsed_changelog'),
					'play_count' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10, 'after' => 'released'),
					'slug' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'play_count'),
					'short_words' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'slug'),
					'created' => array('type' => 'datetime', 'null' => false, 'default' => NULL, 'after' => 'short_words'),
					'modified' => array('type' => 'datetime', 'null' => false, 'default' => NULL, 'after' => 'created'),
					'g_ver' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 45, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'modified'),
					'support_email' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'g_ver'),
					'fbpage_id' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 50, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'support_email'),
					'support_devices' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 45, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'fbpage_id'),
					'appstore_link' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'support_devices'),
					'jailbreak_link' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'appstore_link'),
					'app_gaid' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 45, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'jailbreak_link'),
					'dashboard_gaid' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 45, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'app_gaid'),
					'app_theme' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 45, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'dashboard_gaid'),
					'app_testflightid' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 45, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'app_theme'),
					'app_paypalid' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 45, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'app_testflightid'),
					'forum_link' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'app_paypalid'),
					'language_default' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 45, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'forum_link'),
					'status' => array('type' => 'boolean', 'null' => false, 'default' => '0', 'after' => 'language_default'),
					'apns' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 45, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'status'),
					'alias' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 64, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'apns'),
					'os' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 16, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'alias'),
					'website_id' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10, 'after' => 'os'),
					'gcm_key' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'website_id'),
					'fb_appid' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 45, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'gcm_key'),
					'fb_appsecret' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 45, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'fb_appid'),
					'paypal' => array('type' => 'text', 'null' => true, 'default' => NULL, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'fb_appsecret'),
					'screen' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 45, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'paypal'),
					'data' => array('type' => 'text', 'null' => true, 'default' => NULL, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'screen'),
					'show_on_mobpage' => array('type' => 'boolean', 'null' => true, 'default' => '0', 'after' => 'data'),
					'version_code' => array('type' => 'integer', 'null' => false, 'default' => '1', 'after' => 'show_on_mobpage'),
					'mobhub_link' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'version_code'),
					'mobhub_published' => array('type' => 'boolean', 'null' => false, 'default' => '0', 'after' => 'mobhub_link'),
					'mobhub_description' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'mobhub_published'),
					'mobhub_package' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'mobhub_description'),
					'mobhub_md5' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 32, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'mobhub_package'),
					'last_username' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'mobhub_md5'),
					'show_on_funtap' => array('type' => 'boolean', 'null' => true, 'default' => '0', 'after' => 'last_username'),
					'published_date' => array('type' => 'datetime', 'null' => true, 'default' => NULL, 'after' => 'show_on_funtap'),
					'show_on_mail' => array('type' => 'integer', 'null' => true, 'default' => '0', 'length' => 2, 'after' => 'published_date'),
					'show_on_gate_app' => array('type' => 'boolean', 'null' => false, 'default' => '0', 'after' => 'show_on_mail'),
					'show_image_gate_app' => array('type' => 'boolean', 'null' => false, 'default' => '0', 'after' => 'show_on_gate_app'),
					'group' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 45, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'show_image_gate_app'),
					'hide_all_payment' => array('type' => 'integer', 'null' => true, 'default' => '0', 'length' => 4, 'after' => 'group'),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
						'app_key' => array('column' => 'app', 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_unicode_ci', 'engine' => 'InnoDB'),
				),
				'games_genres' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'game_id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'after' => 'id'),
					'genre_id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'after' => 'game_id'),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_unicode_ci', 'engine' => 'InnoDB'),
				),
				'genres' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'key' => 'primary'),
					'title' => array('type' => 'string', 'null' => false, 'default' => NULL, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'id'),
					'description' => array('type' => 'text', 'null' => false, 'default' => NULL, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'title'),
					'created' => array('type' => 'datetime', 'null' => false, 'default' => NULL, 'after' => 'description'),
					'modified' => array('type' => 'datetime', 'null' => false, 'default' => NULL, 'after' => 'created'),
					'slug' => array('type' => 'string', 'null' => false, 'default' => NULL, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'modified'),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_unicode_ci', 'engine' => 'InnoDB'),
				),
				'i18n' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'locale' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 6, 'key' => 'index', 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'id'),
					'model' => array('type' => 'string', 'null' => false, 'default' => NULL, 'key' => 'index', 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'locale'),
					'foreign_key' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'index', 'after' => 'model'),
					'field' => array('type' => 'string', 'null' => false, 'default' => NULL, 'key' => 'index', 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'foreign_key'),
					'content' => array('type' => 'text', 'null' => true, 'default' => NULL, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'field'),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
						'locale' => array('column' => 'locale', 'unique' => 0),
						'model' => array('column' => 'model', 'unique' => 0),
						'row_id' => array('column' => 'foreign_key', 'unique' => 0),
						'field' => array('column' => 'field', 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_unicode_ci', 'engine' => 'InnoDB'),
				),
				'log_entergames' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'user_id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'index', 'after' => 'id'),
					'game_id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'after' => 'user_id'),
					'g_ver' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 45, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'game_id'),
					'sdk_ver' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 45, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'g_ver'),
					'os' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 45, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'sdk_ver'),
					'device' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 45, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'os'),
					'network' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 45, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'device'),
					'ip' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 45, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'network'),
					'role_id' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 45, 'key' => 'index', 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'ip'),
					'area_id' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 45, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'role_id'),
					'created' => array('type' => 'datetime', 'null' => false, 'default' => NULL, 'after' => 'area_id'),
					'modified' => array('type' => 'datetime', 'null' => false, 'default' => NULL, 'after' => 'created'),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
						'user_id_created' => array('column' => array('user_id', 'created'), 'unique' => 0),
						'role_id_game_id_area_id_created' => array('column' => array('role_id', 'game_id', 'created', 'area_id'), 'unique' => 0),
						'role_id_game_id_created' => array('column' => array('role_id', 'game_id', 'created'), 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_unicode_ci', 'engine' => 'InnoDB'),
				),
				'log_logins' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'user_id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'index', 'after' => 'id'),
					'created' => array('type' => 'datetime', 'null' => false, 'default' => NULL, 'key' => 'index', 'after' => 'user_id'),
					'modified' => array('type' => 'datetime', 'null' => false, 'default' => NULL, 'after' => 'created'),
					'os' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 45, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'modified'),
					'resolution' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 45, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'os'),
					'sdk_ver' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 45, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'resolution'),
					'game_id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'after' => 'sdk_ver'),
					'g_ver' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 45, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'game_id'),
					'device' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 45, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'g_ver'),
					'network' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 45, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'device'),
					'ip' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 45, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'network'),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
						'user_id_created' => array('column' => array('user_id', 'created'), 'unique' => 0),
						'created_game_id' => array('column' => array('created', 'game_id'), 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_unicode_ci', 'engine' => 'InnoDB'),
				),
				'permissions' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'user_id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'index', 'after' => 'id'),
					'model' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 45, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'user_id'),
					'foreign_key' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'after' => 'model'),
					'type' => array('type' => 'string', 'null' => false, 'default' => 'None', 'length' => 45, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'foreign_key'),
					'access' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 4, 'after' => 'type'),
					'created' => array('type' => 'datetime', 'null' => false, 'default' => NULL, 'after' => 'access'),
					'modified' => array('type' => 'datetime', 'null' => false, 'default' => NULL, 'after' => 'created'),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
						'user_id' => array('column' => 'user_id', 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_unicode_ci', 'engine' => 'InnoDB'),
				),
				'profiles' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'user_id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'index', 'after' => 'id'),
					'email_contact' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8', 'after' => 'user_id'),
					'email_contact_token' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8', 'after' => 'email_contact'),
					'email_contact_token_expires' => array('type' => 'datetime', 'null' => true, 'default' => NULL, 'after' => 'email_contact_token'),
					'email_contact_verified' => array('type' => 'boolean', 'null' => false, 'default' => '0', 'after' => 'email_contact_token_expires'),
					'created' => array('type' => 'datetime', 'null' => true, 'default' => NULL, 'after' => 'email_contact_verified'),
					'modified' => array('type' => 'datetime', 'null' => true, 'default' => NULL, 'after' => 'created'),
					'fullname' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'modified'),
					'peopleId' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 20, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'fullname'),
					'peopleId_place_get' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'peopleId'),
					'birthday' => array('type' => 'datetime', 'null' => true, 'default' => NULL, 'key' => 'index', 'after' => 'peopleId_place_get'),
					'peopleId_date_get' => array('type' => 'datetime', 'null' => true, 'default' => NULL, 'after' => 'birthday'),
					'phone' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 15, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'peopleId_date_get'),
					'address' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'phone'),
					'province' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'address'),
					'gender' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'province'),
					'question1' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 10, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'gender'),
					'answer1' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'question1'),
					'question2' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'answer1'),
					'answer2' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'question2'),
					'phone_verified' => array('type' => 'boolean', 'null' => true, 'default' => '0', 'after' => 'answer2'),
					'facebook_link' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'phone_verified'),
					'birthday2' => array('type' => 'datetime', 'null' => true, 'default' => NULL, 'key' => 'index', 'after' => 'facebook_link'),
					'phone_code' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 8, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'birthday2'),
					'country' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'phone_code'),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
						'user_id' => array('column' => 'user_id', 'unique' => 0),
						'birthday' => array('column' => 'birthday', 'unique' => 0),
						'user_id_and_birthday' => array('column' => array('user_id', 'birthday'), 'unique' => 0),
						'birthday2' => array('column' => 'birthday2', 'unique' => 0),
						'user_id_birthday2' => array('column' => array('user_id', 'birthday2'), 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_unicode_ci', 'engine' => 'InnoDB'),
				),
				'users' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'username' => array('type' => 'string', 'null' => false, 'default' => NULL, 'key' => 'index', 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'id'),
					'name' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'username'),
					'slug' => array('type' => 'string', 'null' => false, 'default' => NULL, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'name'),
					'password' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 128, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'slug'),
					'password_token' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 128, 'key' => 'index', 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'password'),
					'email' => array('type' => 'string', 'null' => true, 'default' => NULL, 'key' => 'unique', 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'password_token'),
					'email_verified' => array('type' => 'boolean', 'null' => true, 'default' => '0', 'after' => 'email'),
					'email_temp_verified' => array('type' => 'integer', 'null' => true, 'default' => '0', 'length' => 3, 'after' => 'email_verified'),
					'email_token' => array('type' => 'string', 'null' => true, 'default' => NULL, 'key' => 'index', 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'email_temp_verified'),
					'email_token_expires' => array('type' => 'datetime', 'null' => true, 'default' => NULL, 'after' => 'email_token'),
					'tos' => array('type' => 'boolean', 'null' => false, 'default' => '0', 'after' => 'email_token_expires'),
					'active' => array('type' => 'boolean', 'null' => false, 'default' => '0', 'after' => 'tos'),
					'last_login' => array('type' => 'datetime', 'null' => true, 'default' => NULL, 'key' => 'index', 'after' => 'active'),
					'last_action' => array('type' => 'datetime', 'null' => true, 'default' => NULL, 'key' => 'index', 'after' => 'last_login'),
					'role' => array('type' => 'string', 'null' => false, 'default' => 'User', 'key' => 'index', 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'last_action'),
					'created' => array('type' => 'datetime', 'null' => true, 'default' => NULL, 'key' => 'index', 'after' => 'role'),
					'modified' => array('type' => 'datetime', 'null' => true, 'default' => NULL, 'after' => 'created'),
					'facebook_uid' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 100, 'key' => 'index', 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'modified'),
					'device_id' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 100, 'key' => 'index', 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'facebook_uid'),
					'updated' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10, 'after' => 'device_id'),
					'fb_verified' => array('type' => 'boolean', 'null' => true, 'default' => NULL, 'after' => 'updated'),
					'description' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'fb_verified'),
					'country_code' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 45, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'description'),
					'count_daily' => array('type' => 'integer', 'null' => true, 'default' => '0', 'length' => 10, 'after' => 'country_code'),
					'phone' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 15, 'key' => 'index', 'collate' => 'utf8_unicode_ci', 'comment' => 'phone_login', 'charset' => 'utf8', 'after' => 'count_daily'),
					'phone_verified' => array('type' => 'boolean', 'null' => true, 'default' => '0', 'after' => 'phone'),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
						'email_unique' => array('column' => 'email', 'unique' => 1),
						'BY_USERNAME' => array('column' => 'username', 'unique' => 0),
						'BY_EMAIL' => array('column' => 'email', 'unique' => 0),
						'created' => array('column' => 'created', 'unique' => 0),
						'last_action_user' => array('column' => 'last_action', 'unique' => 0),
						'device_id_email' => array('column' => array('device_id', 'email'), 'unique' => 0),
						'facebook_uid' => array('column' => 'facebook_uid', 'unique' => 0),
						'last_action' => array('column' => 'last_login', 'unique' => 0),
						'role' => array('column' => 'role', 'unique' => 0),
						'email_token' => array('column' => 'email_token', 'unique' => 0),
						'password_token' => array('column' => 'password_token', 'unique' => 0),
						'phone' => array('column' => 'phone', 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_unicode_ci', 'engine' => 'InnoDB'),
				),
				'variables' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'name' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 45, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'id'),
					'value' => array('type' => 'text', 'null' => false, 'default' => NULL, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'name'),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_unicode_ci', 'engine' => 'InnoDB'),
				),
				'websites' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'title' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 45, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'id'),
					'url' => array('type' => 'string', 'null' => false, 'default' => NULL, 'collate' => 'utf8_unicode_ci', 'comment' => 'use SERVER_NAME', 'charset' => 'utf8', 'after' => 'title'),
					'theme2' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 45, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'url'),
					'url2' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'theme2'),
					'game_id' => array('type' => 'integer', 'null' => true, 'default' => NULL, 'length' => 10, 'after' => 'url2'),
					'theme' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 45, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'game_id'),
					'theme_mobile' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 45, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'theme'),
					'created' => array('type' => 'datetime', 'null' => false, 'default' => NULL, 'after' => 'theme_mobile'),
					'modified' => array('type' => 'datetime', 'null' => false, 'default' => NULL, 'after' => 'created'),
					'lang' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 45, 'collate' => 'utf8_unicode_ci', 'charset' => 'utf8', 'after' => 'modified'),
					'published' => array('type' => 'boolean', 'null' => false, 'default' => '0', 'after' => 'lang'),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_unicode_ci', 'engine' => 'InnoDB'),
				),
			),
		),
		'down' => array(
			'drop_table' => array(
				'access_token', 'accounts', 'articles', 'categories', 'games', 'games_genres', 'genres', 'i18n', 'log_entergames', 'log_logins', 'permissions', 'profiles', 'users', 'variables', 'websites'
			),
		),
	);

/**
 * Before migration callback
 *
 * @param string $direction, up or down direction of migration process
 * @return boolean Should process continue
 * @access public
 */
	public function before($direction) {
		return true;
	}

/**
 * After migration callback
 *
 * @param string $direction, up or down direction of migration process
 * @return boolean Should process continue
 * @access public
 */
	public function after($direction) {
		return true;
	}
}
